version: '3.9'

networks:
  tig-net:
    driver: bridge

services:

  tsadmin:
    image: timeseriesadmin/timeseriesadmin:latest
    container_name: tsadmin
    ports:
      - 8085:8085
    networks:
      - tig-net

  http-data:
    build: http-data
    container_name: http-data
    ports:
      - 4000:4000
    networks:
      - tig-net

  influxdb:
    image: influxdb:1.8.6
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "mydata"
      INFLUXDB_ADMIN_USER: "file"
      INFLUXDB_ADMIN_PASSWORD: "accelerator"
    networks:
      - tig-net

  grafana:
    image: grafana/grafana:8.2.1
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - tig-net
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    restart: always

  telegraf:
    image: telegraf:1.19.0
    depends_on:
      - "influxdb"
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "mydata"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    networks:
      - tig-net
    privileged: true
